// <auto-generated />
using System;
using LaunchPad.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaunchPad.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LaunchPadDbContext))]
    [Migration("20260815164324_AddDeliverableProjectTodoLink")]
    partial class AddDeliverableProjectTodoLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaunchPad.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"));

                    b.Property<string>("AvatarBlobPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EntraObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Upn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("AppUserId");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("AppUser", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("MatchRationale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MatchScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("OpsApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OpsApprovedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SponsorApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SponsorApprovedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("UX_Assignment_Active")
                        .HasFilter("[Status] IN (2,3)");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assignment", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<long>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditEventId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ActorAppUserId")
                        .HasColumnType("int");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("AuditEventId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditEvent", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CohortId")
                        .HasColumnType("int");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Gpa")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateOnly?>("GraduationDate")
                        .HasColumnType("date");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResumeBlobPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CandidateId");

                    b.HasIndex("CohortId");

                    b.HasIndex("AppUserId", "CohortId")
                        .IsUnique();

                    b.ToTable("Candidate", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.CandidateRisk", b =>
                {
                    b.Property<decimal?>("AvgScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("HasEngagementRisk")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPerformanceRisk")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MidScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StaleTodoCount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vCandidateRisk", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.CandidateSkill", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<byte>("Proficiency")
                        .HasColumnType("tinyint");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.HasKey("CandidateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkill", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Cohort", b =>
                {
                    b.Property<int>("CohortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CohortId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CohortId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Cohort", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.CommunityComment", b =>
                {
                    b.Property<int>("CommunityCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommunityCommentId"));

                    b.Property<int>("AuthorAppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CommunityPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CommunityCommentId");

                    b.HasIndex("AuthorAppUserId");

                    b.HasIndex("CommunityPostId");

                    b.ToTable("CommunityComment", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.CommunityPost", b =>
                {
                    b.Property<int>("CommunityPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommunityPostId"));

                    b.Property<int>("AuthorAppUserId")
                        .HasColumnType("int");

                    b.Property<string>("AuthorRoleLabel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.HasKey("CommunityPostId");

                    b.HasIndex("AuthorAppUserId");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("CommunityPost", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.CommunityPostReaction", b =>
                {
                    b.Property<int>("CommunityPostId")
                        .HasColumnType("int");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CommunityPostId", "AppUserId");

                    b.HasIndex("AppUserId");

                    b.ToTable("CommunityPostReaction", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Deliverable", b =>
                {
                    b.Property<int>("DeliverableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliverableId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("ProjectTodoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("DeliverableId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ProjectTodoId");

                    b.ToTable("Deliverable", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("RecipientAppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("NotificationId");

                    b.HasIndex("RecipientAppUserId", "IsRead");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Program", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProgramId");

                    b.ToTable("Program", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<int>("AvailabilityNeeded")
                        .HasColumnType("int");

                    b.Property<int>("CohortId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("MaxCandidates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("CohortId");

                    b.HasIndex("SponsorId");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.ProjectInterest", b =>
                {
                    b.Property<int>("ProjectInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectInterestId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectInterestId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("CandidateId", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProjectInterest_Candidate_Project");

                    b.ToTable("ProjectInterest", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.ProjectSkill", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.HasKey("ProjectId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkill", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.ProjectTodo", b =>
                {
                    b.Property<int>("ProjectTodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectTodoId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ProjectTodoId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("ProjectTodo", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<byte?>("Availability")
                        .HasColumnType("tinyint");

                    b.Property<int>("Checkpoint")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Commitment")
                        .HasColumnType("tinyint");

                    b.Property<string>("GrowthAreas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Guidance")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("OutputQuality")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("OverallScore")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(5,2)")
                        .HasComputedColumnSql("CAST((ISNULL([Commitment],0)+ISNULL([Availability],0)+ISNULL([Guidance],0)+ISNULL([OutputQuality],0)) AS DECIMAL(5,2)) / NULLIF((CASE WHEN [Commitment] IS NULL THEN 0 ELSE 1 END) + (CASE WHEN [Availability] IS NULL THEN 0 ELSE 1 END) + (CASE WHEN [Guidance] IS NULL THEN 0 ELSE 1 END) + (CASE WHEN [OutputQuality] IS NULL THEN 0 ELSE 1 END), 0)", true);

                    b.Property<bool?>("RecommendConversion")
                        .HasColumnType("bit");

                    b.Property<int>("ReviewType")
                        .HasColumnType("int");

                    b.Property<string>("Strengths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmittedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ReviewId");

                    b.HasIndex("AssignmentId", "ReviewType", "Checkpoint", "SubmittedBy")
                        .IsUnique()
                        .HasDatabaseName("UX_Review_Once");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SkillCategoryId")
                        .HasColumnType("int");

                    b.HasKey("SkillId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SkillCategoryId");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.SkillCategory", b =>
                {
                    b.Property<int>("SkillCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillCategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SkillCategory", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Sponsor", b =>
                {
                    b.Property<int>("SponsorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SponsorId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RemovalReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SponsorId");

                    b.HasIndex("AppUserId");

                    b.ToTable("Sponsor", (string)null);
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.Candidate", "Candidate")
                        .WithMany("Assignments")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaunchPad.Domain.Entities.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaunchPad.Domain.Entities.Cohort", "Cohort")
                        .WithMany("Candidates")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.CandidateSkill", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.Candidate", "Candidate")
                        .WithMany("Skills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaunchPad.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Cohort", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.Program", "Program")
                        .WithMany("Cohorts")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.CommunityComment", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.AppUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaunchPad.Domain.Entities.CommunityPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("CommunityPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.CommunityPost", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.AppUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.CommunityPostReaction", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaunchPad.Domain.Entities.CommunityPost", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("CommunityPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Deliverable", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.Assignment", "Assignment")
                        .WithMany("Deliverables")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaunchPad.Domain.Entities.ProjectTodo", "ProjectTodo")
                        .WithMany()
                        .HasForeignKey("ProjectTodoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assignment");

                    b.Navigation("ProjectTodo");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Notification", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.AppUser", "RecipientAppUser")
                        .WithMany()
                        .HasForeignKey("RecipientAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientAppUser");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Project", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.Cohort", "Cohort")
                        .WithMany("Projects")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaunchPad.Domain.Entities.Sponsor", "Sponsor")
                        .WithMany("Projects")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.ProjectInterest", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaunchPad.Domain.Entities.Project", "Project")
                        .WithMany("Interests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.ProjectSkill", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.Project", "Project")
                        .WithMany("Skills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaunchPad.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.ProjectTodo", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.Assignment", "Assignment")
                        .WithMany("Todos")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Review", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.Assignment", "Assignment")
                        .WithMany("Reviews")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Skill", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.SkillCategory", "SkillCategory")
                        .WithMany("Skills")
                        .HasForeignKey("SkillCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SkillCategory");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Sponsor", b =>
                {
                    b.HasOne("LaunchPad.Domain.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Assignment", b =>
                {
                    b.Navigation("Deliverables");

                    b.Navigation("Reviews");

                    b.Navigation("Todos");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Cohort", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.CommunityPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Program", b =>
                {
                    b.Navigation("Cohorts");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Project", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Interests");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.SkillCategory", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("LaunchPad.Domain.Entities.Sponsor", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
